name: asset_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    # animation text
  animated_text_kit: ^4.2.2
  # firebase packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  # state management
  provider: ^6.1.2
  # socket
  web_socket_channel:
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
